In [1]:
import sys

sys.path.append("../")

from src.data_loader import download_prices

In [2]:
tickers = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "META",
    "JPM",
    "BAC",
    "KO",
    "PEP",
    "V",
    "MA",
    "XOM",
    "CVX",
    "JNJ",
    "PG",
    "WMT",
    "HD",
    "MCD",
    "SBUX"
]


prices = download_prices(
    tickers
)


prices.head()

[*********************100%***********************]  20 of 20 completed

Ticker,AAPL,AMZN,BAC,CVX,GOOGL,HD,JNJ,JPM,KO,MA,MCD,META,MSFT,NVDA,PEP,PG,SBUX,V,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.192604,15.4260,14.050793,68.898338,26.244781,78.780350,76.110909,46.066780,29.390274,79.714676,69.804466,77.767075,39.681744,0.482423,66.582924,65.555763,32.260994,61.088104,23.127542,57.145554
2015-01-05,23.511065,15.1095,13.642614,66.144341,25.744715,77.127518,75.579308,44.636642,29.390274,77.472473,69.033524,76.518066,39.316833,0.474275,66.082375,65.244041,31.643021,59.739658,23.060234,55.581917
2015-01-06,23.513273,14.7645,13.234435,66.113792,25.109354,76.891373,75.207924,43.479275,29.613434,77.305023,69.160774,75.487099,38.739761,0.459895,65.581764,64.946877,31.385550,59.354717,23.237928,55.286449
2015-01-07,23.842978,14.9210,13.297234,66.058678,25.035503,79.526802,76.868225,43.545609,29.983086,78.507484,70.365829,75.487099,39.231968,0.458697,67.499466,65.287560,32.158001,60.149960,23.854486,55.846645
2015-01-08,24.759089,15.0230,13.571970,67.570320,25.122730,81.286270,77.472626,44.518707,30.345755,79.728645,70.627785,77.499435,40.386089,0.475952,68.726227,66.034149,32.676929,60.956718,24.357960,56.776211

In [3]:
import sys

sys.path.append("../")


from src.data_loader import download_prices
from src.factors import calculate_momentum

In [4]:
tickers = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "META",
    "JPM",
    "BAC",
    "KO",
    "PEP",
    "V",
    "MA",
    "XOM",
    "CVX",
    "JNJ",
    "PG",
    "WMT",
    "HD",
    "MCD",
    "SBUX"
]


prices = download_prices(
    tickers
)

[*********************100%***********************]  20 of 20 completed

In [5]:
momentum = calculate_momentum(
    prices
)


momentum.tail()

Ticker,AAPL,AMZN,BAC,CVX,GOOGL,HD,JNJ,JPM,KO,MA,MCD,META,MSFT,NVDA,PEP,PG,SBUX,V,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,
2025-12-23,0.095287,0.039635,0.320109,0.115743,0.674082,-0.081683,0.477079,0.428698,0.151824,0.107746,0.095994,0.119997,0.122215,0.448284,-0.013523,-0.131374,-0.030122,0.130240,0.198732,0.173376
2025-12-24,0.080783,0.033167,0.302984,0.102392,0.647355,-0.093226,0.482247,0.414723,0.153932,0.103686,0.095525,0.144220,0.126019,0.400606,-0.021637,-0.117533,-0.013126,0.125751,0.221578,0.167427
2025-12-26,0.075867,0.033147,0.309431,0.097954,0.617109,-0.086507,0.473020,0.404637,0.153116,0.102031,0.091443,0.109247,0.128794,0.364517,-0.011662,-0.116269,-0.001157,0.127046,0.248584,0.161632
2025-12-29,0.065059,0.013185,0.276069,0.098369,0.605161,-0.101044,0.466668,0.364382,0.149426,0.084953,0.073936,0.087235,0.116913,0.342686,-0.018362,-0.121643,-0.023003,0.113765,0.225800,0.174376
2025-12-30,0.059050,0.024136,0.269592,0.106894,0.610834,-0.101622,0.464787,0.358339,0.152906,0.083162,0.069249,0.107235,0.120897,0.340608,-0.016526,-0.131078,-0.047319,0.109755,0.217710,0.177862

In [6]:
latest_momentum = (
    momentum
    .iloc[-1]
    .sort_values(
        ascending=False
    )
)


latest_momentum

Ticker
GOOGL    0.610834
JNJ      0.464787
JPM      0.358339
NVDA     0.340608
BAC      0.269592
WMT      0.217710
XOM      0.177862
KO       0.152906
MSFT     0.120897
V        0.109755
META     0.107235
CVX      0.106894
MA       0.083162
MCD      0.069249
AAPL     0.059050
AMZN     0.024136
PEP     -0.016526
SBUX    -0.047319
HD      -0.101622
PG      -0.131078
Name: 2025-12-30 00:00:00, dtype: float64

In [7]:
from src.factors import calculate_volatility

In [8]:
volatility = calculate_volatility(
    prices
)

In [9]:
latest_volatility = (
    volatility
    .iloc[-1]
    .sort_values()
)


latest_volatility

Ticker
KO       0.174634
MCD      0.184918
PG       0.188997
JNJ      0.195444
V        0.224709
PEP      0.226496
MA       0.226860
HD       0.230737
XOM      0.233818
CVX      0.242041
MSFT     0.242715
JPM      0.247804
WMT      0.250606
BAC      0.266322
GOOGL    0.322966
AAPL     0.324449
SBUX     0.340260
AMZN     0.343385
META     0.379051
NVDA     0.495300
Name: 2025-12-30 00:00:00, dtype: float64

In [10]:
import pandas as pd

fundamentals = pd.read_csv(
    "../data/raw/fundamentals.csv"
)

fundamentals.head()

  Ticker   ROE
0   AAPL  1.56
1   MSFT  0.35
2   NVDA  0.45
3  GOOGL  0.30
4   META  0.32

In [11]:
from src.quality import calculate_quality

quality = calculate_quality(
    fundamentals
)

quality

   Ticker   ROE
0    AAPL  1.56
11     MA  1.20
9     PEP  0.58
10      V  0.52
2    NVDA  0.45
8      KO  0.41
18    MCD  0.38
1    MSFT  0.35
19   SBUX  0.35
4    META  0.32
17     HD  0.31
3   GOOGL  0.30
15     PG  0.27
14    JNJ  0.22
16    WMT  0.21
5    AMZN  0.18
6     JPM  0.16
12    XOM  0.15
13    CVX  0.13
7     BAC  0.09

In [12]:
from src.composite import calculate_factor_score

In [13]:
latest_momentum = momentum.iloc[-1]

latest_volatility = volatility.iloc[-1]


quality_data = fundamentals.set_index(
    "Ticker"
)

In [14]:
factor_ranking = calculate_factor_score(
    latest_momentum,
    latest_volatility,
    quality_data
)


factor_ranking

        Momentum  Quality  LowVol  Composite
Ticker
KO          0.65    0.750    0.95     0.7700
JNJ         0.95    0.350    0.80     0.7250
V           0.55    0.850    0.75     0.7000
MA          0.40    0.950    0.65     0.6400
MCD         0.35    0.700    0.90     0.6200
GOOGL       1.00    0.450    0.25     0.6100
NVDA        0.85    0.800    0.00     0.5800
MSFT        0.60    0.625    0.45     0.5625
PEP         0.20    0.900    0.70     0.5600
JPM         0.90    0.200    0.40     0.5400
WMT         0.75    0.300    0.35     0.4950
XOM         0.70    0.150    0.55     0.4900
AAPL        0.30    1.000    0.20     0.4800
BAC         0.80    0.050    0.30     0.4250
PG          0.05    0.400    0.85     0.3950
META        0.50    0.550    0.05     0.3800
HD          0.10    0.500    0.60     0.3700
CVX         0.45    0.100    0.50     0.3600
SBUX        0.15    0.625    0.15     0.2925
AMZN        0.25    0.250    0.10     0.2050

In [15]:
from src.portfolio import create_factor_portfolios

In [16]:
long_stocks, short_stocks = create_factor_portfolios(
    factor_ranking
)


long_stocks, short_stocks

(['KO', 'JNJ', 'V', 'MA'], ['HD', 'CVX', 'SBUX', 'AMZN'])

In [17]:
from src.backtest import calculate_long_short_returns

In [18]:
long_returns, short_returns, factor_returns = calculate_long_short_returns(
    prices,
    long_stocks,
    short_stocks
)

In [19]:
factor_returns.head()

Date
2015-01-02         NaN
2015-01-05    0.010860
2015-01-06    0.007142
2015-01-07   -0.001285
2015-01-08   -0.004764
dtype: float64

In [20]:
factor_returns.describe()

count    2764.000000
mean       -0.000101
std         0.009453
min        -0.074959
25%        -0.004870
50%        -0.000049
75%         0.004749
max         0.077093
dtype: float64

In [21]:
from src.performance import calculate_performance_metrics

In [22]:
factor_metrics = calculate_performance_metrics(
    factor_returns
)

factor_metrics

   Annual Return  Sharpe Ratio  Max Drawdown
0      -0.001749     -0.053408     -0.474501

In [23]:
prices.index.min(), prices.index.max(), prices.shape

(Timestamp('2015-01-02 00:00:00'),
 Timestamp('2025-12-30 00:00:00'),
 (2765, 20))

In [24]:
from importlib import reload
import src.factor_backtest as fb

reload(fb)

from src.factor_backtest import calculate_factor_backtest

In [25]:
factor_returns = calculate_factor_backtest(
    prices,
    fundamentals
)

In [26]:
factor_returns.describe()

count    118.000000
mean       0.014129
std        0.047853
min       -0.132753
25%       -0.015490
50%        0.013661
75%        0.047049
max        0.149187
dtype: float64

In [27]:
factor_metrics = calculate_performance_metrics(
    factor_returns
)

factor_metrics

   Annual Return  Sharpe Ratio  Max Drawdown
0       0.167683      1.011544     -0.208969

In [28]:
from src.capm import capm_regression

In [29]:
market_returns = (
    prices
    .pct_change()
    .mean(axis=1)
)

In [30]:
market_monthly = (
    market_returns
    .resample("ME")
    .sum()
)

In [31]:
aligned_market = (
    market_monthly
    .loc[factor_returns.index]
)

In [32]:
capm_results = capm_regression(
    factor_returns,
    aligned_market
)

capm_results

      Alpha      Beta  R_squared   P_value
0 -0.001288  0.874439   0.576849  0.681272

In [33]:
import os

os.makedirs(
    "../data/raw",
    exist_ok=True
)

In [34]:
prices.to_csv(
    "../data/raw/prices.csv"
)

fundamentals.to_csv(
    "../data/raw/fundamentals.csv",
    index=False
)