In [ ]:
import sys
import os

sys.path.append(
    os.path.abspath("../")
)

from src.data import load_prices
from src.returns import (
    calculate_returns,
    calculate_portfolio_returns
)

In [ ]:
prices = load_prices(
    "../data/raw/prices.csv"
)

prices.head()

,AAPL,AMZN,BAC,CVX,GOOGL,HD,JNJ,JPM,KO,MA,MCD,META,MSFT,NVDA,PEP,PG,SBUX,V,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,
2015-01-02,24.192604,15.4260,14.050793,68.898338,26.244781,78.780350,76.110909,46.066780,29.390274,79.714676,69.804466,77.767075,39.681744,0.482423,66.582924,65.555763,32.260994,61.088104,23.127542,57.145554
2015-01-05,23.511065,15.1095,13.642614,66.144341,25.744715,77.127518,75.579308,44.636642,29.390274,77.472473,69.033524,76.518066,39.316833,0.474275,66.082375,65.244041,31.643021,59.739658,23.060234,55.581917
2015-01-06,23.513273,14.7645,13.234435,66.113792,25.109354,76.891373,75.207924,43.479275,29.613434,77.305023,69.160774,75.487099,38.739761,0.459895,65.581764,64.946877,31.385550,59.354717,23.237928,55.286449
2015-01-07,23.842978,14.9210,13.297234,66.058678,25.035503,79.526802,76.868225,43.545609,29.983086,78.507484,70.365829,75.487099,39.231968,0.458697,67.499466,65.287560,32.158001,60.149960,23.854486,55.846645
2015-01-08,24.759089,15.0230,13.571970,67.570320,25.122730,81.286270,77.472626,44.518707,30.345755,79.728645,70.627785,77.499435,40.386089,0.475952,68.726227,66.034149,32.676929,60.956718,24.357960,56.776211

In [ ]:
returns = calculate_returns(
    prices
)

returns.head()

,AAPL,AMZN,BAC,CVX,GOOGL,HD,JNJ,JPM,KO,MA,MCD,META,MSFT,NVDA,PEP,PG,SBUX,V,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,
2015-01-05,-0.028171,-0.020517,-0.029050,-0.039972,-0.019054,-0.020980,-0.006985,-0.031045,0.000000,-0.028128,-0.011044,-0.016061,-0.009196,-0.016890,-0.007518,-0.004755,-0.019155,-0.022074,-0.002910,-0.027362
2015-01-06,0.000094,-0.022833,-0.029919,-0.000462,-0.024679,-0.003062,-0.004914,-0.025929,0.007593,-0.002161,0.001843,-0.013474,-0.014677,-0.030319,-0.007576,-0.004555,-0.008137,-0.006444,0.007706,-0.005316
2015-01-07,0.014022,0.010600,0.004745,-0.000834,-0.002941,0.034275,0.022076,0.001526,0.012483,0.015555,0.017424,0.000000,0.012705,-0.002605,0.029241,0.005246,0.024612,0.013398,0.026532,0.010133
2015-01-08,0.038423,0.006836,0.020661,0.022883,0.003484,0.022124,0.007863,0.022347,0.012096,0.015555,0.003723,0.026658,0.029418,0.037617,0.018174,0.011435,0.016137,0.013412,0.021106,0.016645
2015-01-09,0.001072,-0.011749,-0.017930,-0.019926,-0.012211,-0.017148,-0.013629,-0.017387,-0.011032,-0.012744,-0.012187,-0.005628,-0.008405,0.004029,-0.006770,-0.009331,-0.032731,-0.014823,-0.012380,-0.001410

In [ ]:
n_assets = prices.shape[1]

weights = [
    1/n_assets
] * n_assets


sum(weights)

1.0

In [ ]:
portfolio_returns = calculate_portfolio_returns(
    returns,
    weights
)

In [ ]:
portfolio_returns.describe()

count    2764.000000
mean        0.000797
std         0.011221
min        -0.123164
25%        -0.003543
50%         0.001028
75%         0.005999
max         0.110844
dtype: float64

In [ ]:
from src.historical_var import (
    historical_var,
    historical_var_amount
)

In [ ]:
portfolio_value = 100000

var95 = historical_var(
    portfolio_returns,
    confidence=0.95
)

var95_amount = historical_var_amount(
    portfolio_returns,
    portfolio_value,
    confidence=0.95
)


print("Historical VaR 95%:", var95)
print("Historical VaR 95% (€):", var95_amount)


var99 = historical_var(
    portfolio_returns,
    confidence=0.99
)

print("Historical VaR 99%:", var99)

Historical VaR 95%: 0.015880474928889363
Historical VaR 95% (€): 1588.0474928889364
Historical VaR 99%: 0.03227333492846372

In [ ]:
from src.parametric_var import (
    parametric_var,
    parametric_var_amount
)

In [ ]:
param95 = parametric_var(
    portfolio_returns,
    confidence=0.95
)


param95_amount = parametric_var_amount(
    portfolio_returns,
    portfolio_value,
    confidence=0.95
)


param99 = parametric_var(
    portfolio_returns,
    confidence=0.99
)


print("Parametric VaR 95%:", param95)
print("Parametric VaR 95% (€):", param95_amount)
print("Parametric VaR 99%:", param99)

Parametric VaR 95%: 0.017659929086774502
Parametric VaR 95% (€): 1765.9929086774503
Parametric VaR 99%: 0.025307170076960605

In [ ]:
from src.monte_carlo_var import (
    monte_carlo_var,
    monte_carlo_var_amount
)

In [ ]:
mc95 = monte_carlo_var(
    portfolio_returns,
    confidence=0.95
)


mc95_amount = monte_carlo_var_amount(
    portfolio_returns,
    portfolio_value,
    confidence=0.95
)


mc99 = monte_carlo_var(
    portfolio_returns,
    confidence=0.99
)


print("Monte Carlo VaR 95%:", mc95)
print("Monte Carlo VaR 95% (€):", mc95_amount)
print("Monte Carlo VaR 99%:", mc99)

Monte Carlo VaR 95%: 0.017691721816446397
Monte Carlo VaR 95% (€): 1755.5168422730367
Monte Carlo VaR 99%: 0.025495666039697183

In [ ]:
from src.expected_shortfall import (
    expected_shortfall,
    expected_shortfall_amount
)

In [ ]:
es95 = expected_shortfall(
    portfolio_returns,
    confidence=0.95
)


es95_amount = expected_shortfall_amount(
    portfolio_returns,
    portfolio_value,
    confidence=0.95
)


es99 = expected_shortfall(
    portfolio_returns,
    confidence=0.99
)


print("Expected Shortfall 95%:", es95)
print("Expected Shortfall 95% (€):", es95_amount)
print("Expected Shortfall 99%:", es99)

Expected Shortfall 95%: 0.026819290317704948
Expected Shortfall 95% (€): 2681.929031770495
Expected Shortfall 99%: 0.04669510254482583

In [ ]:
from src.risk_report import create_risk_report

In [ ]:
risk_report = create_risk_report(

    historical95=var95,
    historical99=var99,

    parametric95=param95,
    parametric99=param99,

    monte_carlo95=mc95,
    monte_carlo99=mc99,

    es95=es95,
    es99=es99,

    portfolio_value=portfolio_value

)


risk_report

               Metric       95%       99%      95% (€)      99% (€)
0      Historical VaR  0.015880  0.032273  1588.047493  3227.333493
1      Parametric VaR  0.017660  0.025307  1765.992909  2530.717008
2     Monte Carlo VaR  0.017692  0.025496  1769.172182  2549.566604
3  Expected Shortfall  0.026819  0.046695  2681.929032  4669.510254

In [ ]:
from src.plotting import (
    plot_return_distribution,
    plot_cumulative_returns
)

In [ ]:
plot_return_distribution(
    portfolio_returns,
    var=var95,
    es=es95
)

In [ ]:
plot_cumulative_returns(
    portfolio_returns
)

In [ ]:
from src.stress_analysis import worst_loss_days
worst_days = worst_loss_days(
    portfolio_returns,
    portfolio_value=100000,
    n_days=10
)


worst_days

              Return      Loss (€)
Date
2020-03-16 -0.123164 -12316.399539
2020-03-12 -0.092438  -9243.773165
2020-03-09 -0.075929  -7592.877794
2020-06-11 -0.057442  -5744.232238
2025-04-04 -0.055686  -5568.571172
2020-03-18 -0.052781  -5278.066036
2020-03-11 -0.047362  -4736.239354
2020-02-27 -0.046111  -4611.080577
2020-03-20 -0.046067  -4606.726899
2018-02-05 -0.043708  -4370.810966

In [ ]:
from src.crisis_analysis import analyze_crisis

In [ ]:
covid = analyze_crisis(
    portfolio_returns,
    "2020-02-01",
    "2020-04-30"
)

covid

{'Total Return': np.float64(-0.07607562565278592),
 'Maximum Drawdown': np.float64(-0.3066706153390669),
 'Worst Day': np.float64(-0.12316399539328034),
 'Recovery Days': 74,
 'Bottom Date': Timestamp('2020-03-23 00:00:00')}

In [ ]:
rate_shock = analyze_crisis(
    portfolio_returns,
    "2022-01-01",
    "2022-12-31"
)


rate_shock

{'Total Return': np.float64(-0.1165954482893935),
 'Maximum Drawdown': np.float64(-0.20402125404169663),
 'Worst Day': np.float64(-0.043019584450303926),
 'Recovery Days': 196,
 'Bottom Date': Timestamp('2022-09-30 00:00:00')}