In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [2]:
from src.loader import load_processed_data

df = load_processed_data("Germany")

df.head()

IndexError: list index out of range

In [4]:
from src.loader import load_processed_data

df = load_processed_data()

df.head()

,datetime,load,solar,wind_onshore,wind_offshore,temperature,wind_speed,cloud_cover,solar_radiation,hour,...,month,weekday,weekend,load_lag_1,load_lag_24,load_lag_168,rolling_mean_24,rolling_std_24,hour_sin,hour_cos
0,2015-01-08 00:00:00,48041.0,0.0,15273.0,534.0,1.3,15.3,100,0.0,0,...,1,3,0,50460.0,45125.0,41151.0,60234.500000,8884.334704,0.000000,1.000000
1,2015-01-08 01:00:00,47074.0,0.0,15915.0,533.0,1.0,15.6,100,0.0,1,...,1,3,0,48041.0,44217.0,40135.0,60353.541667,8677.107873,0.258819,0.965926
2,2015-01-08 02:00:00,47228.0,0.0,16164.0,531.0,0.8,15.8,96,0.0,2,...,1,3,0,47074.0,44368.0,39106.0,60472.708333,8465.074306,0.500000,0.866025
3,2015-01-08 03:00:00,48253.0,0.0,16258.0,529.0,1.0,16.1,100,0.0,3,...,1,3,0,47228.0,45298.0,38765.0,60595.833333,8253.609944,0.707107,0.707107
4,2015-01-08 04:00:00,51155.0,0.0,16218.0,532.0,1.2,16.7,100,0.0,4,...,1,3,0,48253.0,48598.0,38941.0,60702.375000,8107.207410,0.866025,0.500000

In [5]:
from src.preprocessing import merge_energy_weather

merged_df = merge_energy_weather()

merged_df.head()

,datetime,load,solar,wind_onshore,wind_offshore,hour,day,month,weekday,temperature,wind_speed,cloud_cover,solar_radiation
0,2014-12-31 23:00:00,NaN,NaN,NaN,NaN,23,31,12,2,NaN,NaN,NaN,NaN
1,2015-01-01 00:00:00,41151.0,NaN,8852.0,517.0,0,1,1,3,3.8,14.4,71.0,0.0
2,2015-01-01 01:00:00,40135.0,NaN,9054.0,514.0,1,1,1,3,3.6,14.9,69.0,0.0
3,2015-01-01 02:00:00,39106.0,NaN,9070.0,518.0,2,1,1,3,3.3,14.6,95.0,0.0
4,2015-01-01 03:00:00,38765.0,NaN,9163.0,520.0,3,1,1,3,3.0,14.1,82.0,0.0

In [6]:
from src.features import create_features


features_df = create_features(
    merged_df
)


features_df.head()

,datetime,load,solar,wind_onshore,wind_offshore,hour,day,month,weekday,temperature,...,cloud_cover,solar_radiation,weekend,load_lag_1,load_lag_24,load_lag_168,rolling_mean_24,rolling_std_24,hour_sin,hour_cos
169,2015-01-08 00:00:00,48041.0,0.0,15807.0,534.0,0,8,1,3,1.3,...,100.0,0.0,0,50460.0,45125.0,41151.0,60113.000000,9076.207612,0.000000,1.000000
170,2015-01-08 01:00:00,47074.0,0.0,16449.0,533.0,1,8,1,3,1.0,...,100.0,0.0,0,48041.0,44217.0,40135.0,60234.500000,8884.334704,0.258819,0.965926
171,2015-01-08 02:00:00,47228.0,0.0,16695.0,531.0,2,8,1,3,0.8,...,96.0,0.0,0,47074.0,44368.0,39106.0,60353.541667,8677.107873,0.500000,0.866025
172,2015-01-08 03:00:00,48253.0,0.0,16787.0,529.0,3,8,1,3,1.0,...,100.0,0.0,0,47228.0,45298.0,38765.0,60472.708333,8465.074306,0.707107,0.707107
173,2015-01-08 04:00:00,51155.0,0.0,16751.0,532.0,4,8,1,3,1.2,...,100.0,0.0,0,48253.0,48598.0,38941.0,60595.833333,8253.609944,0.866025,0.500000

In [7]:
from src.train import train_xgboost


model = train_xgboost(
    features_df,
    "Germany"
)

In [8]:
model

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 2951: character maps to <undefined>

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 2951: character maps to <undefined>

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [9]:
from src.evaluate import evaluate_model


results = evaluate_model(
    model,
    features_df
)


results

{'MAE': 344.8342981824336,
 'RMSE': np.float64(472.3612829193434),
 'MAPE': 0.006388377563306027}

In [10]:
from src.predict import load_model, predict_load

In [11]:
model = load_model(
    "Germany"
)

In [12]:
forecast_df = predict_load(
    model,
    features_df.tail(24)
)

forecast_df

                 datetime      forecast
50377 2020-09-30 00:00:00  43992.050781
50378 2020-09-30 01:00:00  44332.355469
50379 2020-09-30 02:00:00  45645.078125
50380 2020-09-30 03:00:00  49428.230469
50381 2020-09-30 04:00:00  56986.179688
50382 2020-09-30 05:00:00  62070.933594
50383 2020-09-30 06:00:00  64660.769531
50384 2020-09-30 07:00:00  64680.765625
50385 2020-09-30 08:00:00  65836.289062
50386 2020-09-30 09:00:00  66777.226562
50387 2020-09-30 10:00:00  66250.023438
50388 2020-09-30 11:00:00  65579.617188
50389 2020-09-30 12:00:00  64246.441406
50390 2020-09-30 13:00:00  63293.445312
50391 2020-09-30 14:00:00  61930.734375
50392 2020-09-30 15:00:00  60891.500000
50393 2020-09-30 16:00:00  61489.890625
50394 2020-09-30 17:00:00  62830.718750
50395 2020-09-30 18:00:00  61137.378906
50396 2020-09-30 19:00:00  57448.906250
50397 2020-09-30 20:00:00  53293.062500
50398 2020-09-30 21:00:00  49647.800781
50399 2020-09-30 22:00:00  46427.636719
50400 2020-09-30 23:00:00  44939.636719

In [13]:
from src.config import load_country_config

countries = load_country_config()

countries

{'Germany': {'energy_file': 'germany_energy.csv',
  'weather_file': 'weather_germany.csv'}}